# Generated by Django 4.2.29 on 2026-03-08 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('wallet_address', models.CharField(max_length=255)),
                ('network', models.CharField(blank=True, help_text='e.g. ERC-20, TRC-20', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='crypto_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('minimum_deposit', models.DecimalField(decimal_places=8, default=0.001, max_digits=15)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cryptocurrency',
                'verbose_name_plural': 'Cryptocurrencies',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('ABSA', 'ABSA Bank'), ('FNB', 'First National Bank (FNB)'), ('STANDARD', 'Standard Bank'), ('NEDBANK', 'Nedbank'), ('CAPITEC', 'Capitec Bank'), ('INVESTEC', 'Investec')], max_length=20)),
                ('account_holder', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('account_type', models.CharField(default='Cheque', max_length=30)),
                ('branch_code', models.CharField(max_length=10)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('reference_prefix', models.CharField(default='INZ', help_text='Prefix for payment reference (e.g. INZ-<account_number>)', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Platform Bank Account',
            },
        ),
        migrations.CreateModel(
            name='CryptoDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crypto_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('zar_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exchange_rate_used', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_hash', models.CharField(blank=True, max_length=255)),
                ('from_wallet_address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending - Awaiting Transfer'), ('SUBMITTED', 'Submitted - Hash Provided'), ('VERIFYING', 'Verifying on Blockchain'), ('APPROVED', 'Approved & Credited'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_crypto_deposits', to=settings.AUTH_USER_MODEL)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deposits.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crypto Deposit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_reference', models.CharField(max_length=50, unique=True)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='deposit_proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending - Awaiting Payment'), ('SUBMITTED', 'Submitted - Proof Uploaded'), ('VERIFYING', 'Verifying'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deposits', to=settings.AUTH_USER_MODEL)),
                ('platform_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deposits.platformbankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Deposit',
                'ordering': ['-created_at'],
            },
        ),
    ]
