# Generated by Django 4.2.29 on 2026-03-08 10:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expected_roi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expected_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_roi_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('maturity_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Activation'), ('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('gold', 'Gold Bars Icon'), ('real_estate', 'Building Icon'), ('crypto', 'Crypto Coin Icon')], default='gold', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='investment_categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Investment Category',
                'verbose_name_plural': 'Investment Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ROIPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_payments', to='investments.investment')),
            ],
            options={
                'verbose_name': 'ROI Payment',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=500.0, max_digits=12)),
                ('maximum_amount', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=12)),
                ('duration_value', models.PositiveIntegerField(default=30)),
                ('duration_unit', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='DAYS', max_length=10)),
                ('roi_type', models.CharField(choices=[('FIXED', 'Fixed Rate'), ('TIERED', 'Tiered Rate (based on amount)'), ('COMPOUND', 'Compound Interest')], default='FIXED', max_length=10)),
                ('roi_percentage', models.DecimalField(decimal_places=2, help_text='ROI percentage for the full duration period', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(500)])),
                ('daily_roi', models.DecimalField(decimal_places=4, default=0.0, help_text='Auto-calculated daily ROI', max_digits=5)),
                ('returns_principal', models.BooleanField(default=True, help_text='Return capital at maturity')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='investments.investmentcategory')),
            ],
            options={
                'verbose_name': 'Investment Plan',
                'ordering': ['category', 'display_order', 'minimum_amount'],
            },
        ),
        migrations.AddField(
            model_name='investment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='investments.investmentplan'),
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL),
        ),
    ]
