# Generated by Django 4.2.29 on 2026-03-09 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='tax_certificate_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='tax_code',
            field=models.CharField(blank=True, help_text='SARS-issued tax clearance / withholding tax code', max_length=30),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='tax_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tax_certificates/'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawal_code',
            field=models.CharField(blank=True, help_text='Admin-issued one-time withdrawal authorisation code', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawal_code_used',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WithdrawalCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active — not yet used'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=10)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: limit how much this code authorises', max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, help_text='Admin who generated this code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_withdrawal_codes', to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(help_text='User this code is issued to', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal Code',
                'verbose_name_plural': 'Withdrawal Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
