# Generated by Django 4.2.29 on 2026-03-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisionalnotification',
            name='url',
            field=models.CharField(blank=True, default='/', help_text='URL to open when user taps the notification', max_length=255),
        ),
    ]
